name: CI
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
#          - '7.2'
#          - '7.3'
#          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
        dependency-version: [ prefer-stable ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 10

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Install composer dependencies
        uses: ./.github/actions/install-composer-dependencies
        with:
          with-dev: yes
          php-version: ${{ matrix.php }}

      - name: Run tests
        run: composer test

      - if: matrix.php == '8.2'
        name: Generate code coverage
        run: XDEBUG_MODE=coverage php vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

      - if: matrix.php == '8.2'
        name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


